server {
    listen 80;
    server_name localhost;

    # React-Frontend (Default)
    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    # Symfony (Backend)
    location /api {
        alias /var/www/symfony/public;
        try_files $uri /index.php$is_args$args;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass scrumpoker_symfony:9000;
            fastcgi_param SCRIPT_FILENAME $request_filename;
        }
    }
}
